### PR TITLE
SVG mixin fix for iOS

### PR DESCRIPTION
**Pull request by erakor**
I believe this to be a good candidate to be in Solid's mixin library. It helps platform deals with a problem that iOS 8 and below have with SVG.

### CODE REVIEW

**Comment by Ianfeather** [comment]
Can you address this comment? https://github.com/buzzfeed/mono/pull/18007/files#r131891432

**Comment by emilybrick** [comment]
Can you give me more context on this? I don't know what it does

**Comment by erakor** [comment]
@emilybrick Safari on iOS 8 and below doesn't handle SVG (when used as a link) the best way. You need to click precisely on the SVG itself instead of the `block` it might be forming. This mixin adds a transparent layer the size of the block on top of it to help with targeting when taping. Sounds clear? :-)

**Comment by erakor** [comment]
@Ianfeather Fixed that comment. 
Docs update [here](https://github.com/buzzfeed/mono/pull/18102)

**Comment by emilybrick** [comment]
Cool, thanks. Taking a look @ the docs now.

**Pull request closed without merging**
