### PR TITLE
Removed flex beta messaging

### PR DESCRIPTION
**Pull request by emilybrick**

### CODE REVIEW

**Comment by emilybrick** [comment]
Follow up to this -
do some internal research with Solid users @ BuzzFeed to figure out which classes are missing, if any

**Comment by emilybrick** [comment]
bump bump

**Comment by allisonchefec** [comment]
do ittttt

**Comment by allisonchefec** [comment]
does this need to be it's own release? or was flexbox already included in the last release?

**Comment by emilybrick** [comment]
@allisonchefec shouldn't need it's own release. was going to merge and do a release with sam this afternoon (which also includes new colors)

**Pull request merged**
