### PR TITLE
SITE-5296: solid: Make a mixin for the card styles

### PR DESCRIPTION
**Pull request by eventlistener**
Having a mixin for the card styles will allow teams to safely reuse those styles without affecting the original `.card` class.

Before:
```sass
  @import "solid-components/cards";

  .custom-card {
    @extend .card;
  }
```
which compiles to
```css
  .custom-card, .card {
     border: 1px solid rgba(0,0,0,.1);
     border-radius: 3px;
    // ...
  }
```

After:
```sass
  @import "solid-components/cards";

  .custom-card {
    @include card();
  }
```
which compiles to
```css
  .card {
     border: 1px solid rgba(0,0,0,.1);
     border-radius: 3px;
    // ...
  }

  .custom-card {
     border: 1px solid rgba(0,0,0,.1);
     border-radius: 3px;
    // ...
  }
```

### CODE REVIEW

**Comment by allisonchefec** [comment]
@eventlistener i think this mixin should go into the mixin.scss file, not the cards.scss file

**Comment by eventlistener** [comment]
@allisonchefec I thought `mixins.scss` is for general-purpose mixins while mixins relating to particular components should be kept in their respective files? Similar to how it's done with buttons styles
https://github.com/buzzfeed/solid/blob/9e2ad5d1b381cf0f91f0ed24d39699052639d170/_lib/solid-utilities/_buttons.scss#L210-L227

**Comment by allisonchefec** [comment]
oh i'm sorry, you are right 👍

**Comment by eventlistener** [comment]
@allisonchefec Would you help me with publishing `2.11.0`?

**Pull request merged**
