### PR TITLE
SOLID-367 Remove Override For Button Focus Outline

### PR DESCRIPTION
**Pull request by allisonchefec**
Removed outline override for button focus and just left it on :active

Tab through the Buttons page in the Solid docs to see the change. Unfortunately this DOES show up on click because technically you are still focused while you're clicking. I think this is the best solution for now. We can alert designers and solicit feedback from them, but I think the benefits outweigh the negatives here.

### CODE REVIEW

**Comment by emilybrick** [comment]
Hey @samthurman @allisonchefec - this may a super dumb question, but is there a reason we don't just have outline: 0 on the button reset? I'm not sure we need this level of specificity with &:active. Aren't the focus/active states overridden by the !important on the button style.

**Comment by allisonchefec** [comment]
@samthurman i'm SO confused. remember how we saw this change working yesterday? it does NOT appear to be working for me now. this change appears to be doing the same thing it was doing before (hiding the outline at all times). when i comment it out, the outline shows back up again. maybe we should just do that and screw the rest of it. 

@emilybrick not sure what you're asking. i believe this is the right location for this code, however it doesn't appear to be working anyway. so we might just remove it and have the outline show on focus and active.

**Comment by emilybrick** [comment]
Al and I just talked IRL - @samthurman 

Sounds like this branch isn't ready to go out ... my only thought (based on initial comments in the pr) was that if we are going to compromise and **not** have the accessible focus outlines on buttons - then we should remove outline:0 on the active pseudo class and put it on the button itself, that level of specificity isn't doing anything. BUT! I just talked to Al and it sounds like we are not shipping this EITHER way without button outline on focus. 👍

**Comment by allisonchefec** [comment]
OK removed the extra ampersand and pushed

**Comment by allisonchefec** [comment]
nother review here?

**Comment by emilybrick** [comment]
@allisonchefec we are releasing now - you ready to merge this?

**Pull request merged**
