### PR TITLE
SOLID-396: Add Purple and Teal

### PR DESCRIPTION
**Pull request by allisonchefec**
added teal and purple to fill colors, svg fill colors, and text colors

### CODE REVIEW

**Comment by emilybrick** [comment]
this lgtm!

**Comment by allisonchefec** [comment]
@lindseymaratta do you want to look at this?

**Comment by allisonchefec** [comment]
Good point!

Dark teal is pretty dark. 

https://monosnap.com/file/4wcYVccwSsME92Izm5b9Iab1OiGgH9.png

Also as I recall, most of our colors don't have good contrast. :-/

We could also darken the regular teal a bit, somewhere in between regular and dark.

What's the accessibility contrast checker you're using? (I want to use it too!)

**Comment by allisonchefec** [comment]
add purple text but not teal

**Comment by allisonchefec** [comment]
@lindseymaratta removed text-teal but kept svg-teal, is that ok??

**Comment by allisonchefec** [comment]
@lindseymaratta any thoughts on keeping `svg-teal`? also i kept the text-teal variable to use in the `svg-teal` class. Is that gross?

**Comment by lindseymaratta** [comment]
Let's  kill `$text-teal`, keep`$fill-teal` and have `.svg-teal` use the `$fill-teal` variable.

**Comment by allisonchefec** [comment]
done @lindseymaratta

**Comment by emilybrick** [comment]
+++++++

**Pull request merged**
