### PR TITLE
SOLID-396 Add Card Class to the Solid Docs Template

### PR DESCRIPTION
**Pull request by allisonchefec**

### CODE REVIEW

**Comment by lindseymaratta** [comment]
love it

**Comment by lindseymaratta** [comment]
btw i do notice that there is a minor minor style change border-wise from the left col to the card, but it doesn't bother me tbh.

**Comment by emilybrick** [comment]
Hey! This LGTM!

Re: the minor style change between left col and card - I think it's alright as well, we're just missing the the slight box-shadow on the nav, right? Think it's ok.

This can be solved in a follow up (as it's unrelated) ... but this generous spacing underneath the mobile nav is starting to feel egregious to me 
https://www.dropbox.com/s/0rzdkm8afu3o63k/Screenshot%202016-11-07%2009.24.55.png?dl=0

It's nitpicky, but I think we can remove unless there is some reason it's there I'm not aware of. 
This is what it would look like w/ even margin around the mobile card
https://www.dropbox.com/s/29by1rdrwhoqtlo/Screenshot%202016-11-07%2009.25.16.png?dl=0

**Comment by allisonchefec** [comment]
fixed the padding on mweb!

**Pull request merged**
