### PR TITLE
Sold 282 svg icons

### PR DESCRIPTION
**Pull request by lindseymaratta**
I made some updates to this. Still slightly WIP if anyone wants to take a look. Only want to tackle svgs with links (the caret issue) in this iteration, though I left some starter text styles in there commented out (will delete them when ready to merge) I sized the icon a text size smaller than the actual text, because the appropriate size felt kind of weird. Thoughts on that are welcome. Bye.

### CODE REVIEW

**Comment by emilybrick** [comment]
Hey! This is looking good. Slightly confused about some of it tho. I'm prob missing context but would this fall apart if you need to use a diff. size link (text-5 or text-3, for ex)?

I dig how you are targeting the paths specifically. 

I have two bigger questions, though: 

I think we can break this out/iterate into a follow up PR. Right now, we don't have the SVGS at all, and I think shipping the svgs/svg sizing/ non-linked icons (tho I would just call this icons with text) is enough for one release. 

Additionally, if we are going to put the linked icons out - we should do it *with* the svg link hover color/component fix that you and Allison are vetting in the webapp. 
^ I don't think it makes sense for these to be separate. I def think once you've tried it out a bit on the homepage/CMS, we can make a strong case to add this as a follow up (linked SVG's, with the correct link color & hover states)

Idk! I could be wrong. These are just my gut feels.

**Comment by emilybrick** [comment]
Woop! Talked IRL - let us know if you have q'z

**Comment by lindseymaratta** [comment]
I updated this to remove the additional component stuff and accessibility docs that refers to it. This is much simpler, but would really appreciate another review on it for a release today. Also, are we happy shipping these sizes?

**Comment by emilybrick** [comment]
Hey! 
Everything looks good to me on the code side, thanks for scoping this down

Everything LGTM. You are gonna hate me, but I think the descriptive copy at the top could be a bit more explicit. Right now it feels a little barren? Is there a reason it's called brand icon set? Makes me think there is another icon set somewhere, non-brand specific.

### BuzzFeed Icon Set
Our SVG icon set can be accessed by BuzzFeed employees in this [github repository.](https://github.com/buzzfeed/solid-icons). We inline all of our SVGs for performance and accessibility reasons, which you can read more about [here](https://css-tricks.com/icon-fonts-vs-svg/).

**Pull request merged**
